export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT'; 
export const ADDMEDICINE = 'ADDMEDICINE'; 
export const DELETEMEDICINE = 'DELETEMEDICINE';
export const EDITMEDICINE = 'EDITMEDICINE';